version: '3'
services:
  app:
    build: 
      dockerfile: .devcontainer/Dockerfile
      context: ..
    volumes:
      # Use `.npmrc` from user directory
      - ~/.npmrc:/home/node/.npmrc:ro
      - ..:/app:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
